### ISSUE TITLE
A bug in 'Adjust Width' component

### ISSUE THREAD

**Issue by bzsgbq** [sarthak-chakraborty/PARIMA#16]
Your paper has the following description of the adjust weight component:

> The model takes as input the 𝑥 and 𝑦 coordinates (horizontal and vertical components respectively) for the viewports of the previous chunk of frames to predict the viewports for the next chunk of frames. Let (𝑥𝑓 , 𝑦𝑓 ) be the viewport at frame 𝑓 . However, if the viewport wraps around the equirectangular frame to another side of the frame, it would create a discontinuous time series of viewports. To model it as a continuous time series, 𝑥𝑓 needs to be width-adjusted, which is performed by the ‘Adjust Width’ component in Figure 3 using the following transformation:
![image](https://user-images.githubusercontent.com/81854989/232179364-d9d43748-ba0c-429a-9952-8c56f51361cc.png)

However, the above equation does not seem to handle an extreme case: for example, if the user keeps rotating clockwise, crosses the right edge of the ERP frame once, and then crosses the right edge once or more, equation (1) will calculate the wrong result.

I wrote a python script to further illustrate the problem and suggest a solution:
```python
def origin_adjust_width(lst, width):
    x = lst.copy()
    for f in range(1, len(x)):
        if abs(x[f]-x[f-1] + width) < abs(x[f]-x[f-1]):
            x[f] = x[f] + width
        elif abs(x[f]-x[f-1] - width) < abs(x[f]-x[f-1]):
            x[f] = x[f] - width
        else:
            x[f] = x[f]
    return x


def my_adjust_width(lst, width):
    x = lst.copy()
    for f in range(1, len(x)):
        remainder = (x[f] - x[f-1]) % width
        if abs(remainder - width) < abs(remainder):
            remainder = remainder - width
        x[f] = x[f-1] + remainder
    return x


x = [0, 1, 2, 0, 1, 2, 0, 1, 2]
your_res = origin_adjust_width(lst=x, width=3)
my_res = my_adjust_width(lst=x, width=3)
print(your_res)  # [0, 1, 2, 3, 4, 5, 3, 4, 5]
print(my_res)  # [0, 1, 2, 3, 4, 5, 6, 7, 8]
```

**Comment by sarthak-chakraborty** [comment]
Hi, I think you might be right. Let me just re-check it and confirm. Thank you.

**Comment by bzsgbq** [comment]
You’re welcome! It was a pleasure to assist you with this issue! Thank you for your amazing work on this project!
