### ISSUE TITLE
Why not use tot_objects?

### ISSUE THREAD

**Issue by binbinzhm** [sarthak-chakraborty/PARIMA#18]
![image](https://github.com/sarthak-chakraborty/PARIMA/assets/38529221/d40c0797-1b76-41a8-9a87-66da77cfb0db)

**Comment by Tung-I** [comment]
I got the same problem here. It seems the open-sourced code does not include their proposed method that leverages both viewport and object trajectories. Only the ablation without using object trajectories is provided.

**Comment by binbinzhm** [comment]
He placed both viewpoint trajectories and object trajectories in the X.
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sarthak-chakraborty/PARIMA"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月6日(星期一) 凌晨4:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sarthak-chakraborty/PARIMA] Why not use tot_objects? (Issue #18)





 
I got the same problem here. It seems the open-sourced code does not include their proposed method that leverages both viewport and object trajectories. Only the ablation without using object trajectories is provided.
