### ISSUE TITLE
question

### ISSUE THREAD

**Issue by longtao-09** [sarthak-chakraborty/PARIMA#5]
Hello,when I try run the '/Prediction/main.py',there was an error :

**_File "/home/longtao/.local/lib/python3.8/site-packages/creme/linear_model/pa.py", line 94, in fit_one
    tau_x = self.calc_tau(X, self.loss.eval(x, x_pred))
AttributeError: 'EpsilonInsensitiveHinge' object has no attribute 'eval'_**

Whether I need to add 'eval function' in '/creme/optim/losses'?
thank you for your help
![question](https://user-images.githubusercontent.com/82214898/126322876-243857e8-a092-450a-8548-73983d3d73ec.png)

**Comment by sarthak-chakraborty** [comment]
Did you replace the `creme/linear_models/pa.py` file in your system with the one provided along with the source code? If not, can you please follow these steps:

```
After the installation, source code for the package creme needs to be modified. For the same, go to the location(say, PATH) in your system where creme library source codes are stored(eg, ~/anaconda3/lib/python3.7/site-packages/creme/) and copy the file creme/linear_model/pa.py into the appropriate subdirectory in PATH.
```

In `PAReegressor` class, there are a few changes implemented that should be present to run the code. `optim.losses.EpsilonInsensitiveHinge` should contain the attribute 'eval` by default, which was not modified.

**Comment by longtao-09** [comment]
> Did you replace the `creme/linear_models/pa.py` file in your system with the one provided along with the source code? If not, can you please follow these steps:
> 
> ```
> After the installation, source code for the package creme needs to be modified. For the same, go to the location(say, PATH) in your system where creme library source codes are stored(eg, ~/anaconda3/lib/python3.7/site-packages/creme/) and copy the file creme/linear_model/pa.py into the appropriate subdirectory in PATH.
> ```
> 
> In `PAReegressor` class, there are a few changes implemented that should be present to run the code. `optim.losses.EpsilonInsensitiveHinge` should contain the attribute 'eval` by default, which was not modified.

Thank you for your help.But I have replaced `creme/liner_model/pa.py` and I will attach the Debug picture .
There is no use `eval` in the default `pa.py.`
![debug](https://user-images.githubusercontent.com/82214898/126341664-2bd01646-d727-4784-a756-02843895cb2f.png)
![default](https://user-images.githubusercontent.com/82214898/126343292-b7c86597-54b3-49fe-b5bf-a4c3126f65b8.png)

**Comment by sousoul** [comment]
> Did you replace the `creme/linear_models/pa.py` file in your system with the one provided along with the source code? If not, can you please follow these steps:
> 
> ```
> After the installation, source code for the package creme needs to be modified. For the same, go to the location(say, PATH) in your system where creme library source codes are stored(eg, ~/anaconda3/lib/python3.7/site-packages/creme/) and copy the file creme/linear_model/pa.py into the appropriate subdirectory in PATH.
> ```
> 
> In `PAReegressor` class, there are a few changes implemented that should be present to run the code. `optim.losses.EpsilonInsensitiveHinge` should contain the attribute 'eval` by default, which was not modified.

```

class EpsilonInsensitiveHinge(RegressionLoss):
    """Epsilon-insensitive hinge loss.

    Parameters:
        eps

    """

    def __init__(self, eps=.1):
        self.eps = eps

    def __call__(self, y_true, y_pred):
        y_true = y_true * 2 - 1  # [0, 1] -> [-1, 1]

        if isinstance(y_true, np.ndarray):
            return np.maximum(np.abs(y_pred - y_true) - self.eps, 0)

        return max(math.fabs(y_pred - y_true) - self.eps, 0)

    def gradient(self, y_true, y_pred):
        y_true = y_true * 2 - 1  # [0, 1] -> [-1, 1]

        if isinstance(y_true, np.ndarray):
            gradients = np.zeros_like(y_true)
            gradients[y_pred > y_true + self.eps] = 1
            gradients[y_pred + self.eps < y_true] = -1
            return gradients

        if y_pred > y_true + self.eps:
            return 1
        elif y_pred + self.eps < y_true:
            return -1
        return 0
```
I meet the same question, I can't find the attribute 'eval`  of optim.losses.EpsilonInsensitiveHinge and the code of optim.losses.EpsilonInsensitiveHinge is above.

**Comment by sarthak-chakraborty** [comment]
It seems that creme has undergone few structural changes without affecting the semantics of any of the function bodies. Hence the attribute `eval()` of optim.losses.EpsilonInsensitiveHinge has been modified and made a callable method, i.e., used the `__call__()` method of python. Hence, the `self.loss.eval(...)` in pa.py has been restructured to `self.loss(...)`. 

So, we have pushed a new commit where the file `pa.py` is modified, changing `self.loss.eval()` to  `self.loss()`.
