### ISSUE TITLE
Question about the results

### ISSUE THREAD

**Issue by JunhuaLiu0** [sarthak-chakraborty/PARIMA#8]
Hello, I have a similar question with sousoul, about the head_orientation_lib.H and head_orientation_lib.W in head_orientation_lib.
I have a code implementation in 9 nine videos in dataset2. I get the similar QoE in PARIMA and its baseline but a quite different Manhattan Tile Error.
For video football in ds2, the thesis show the error is 0.175. But my result is never lower than 0.5

```
x_pred: 352.10410093526434
y: 128
y_pred: 110.38240202809543
x: 419
x_pred: 352.9224915987684
y: 128
y_pred: 110.28424136246412
Manhattan Tile Error: 0.5094736842105263
MAE: 163.245674 MAE: 62.891378
```
You reply to sousoul to change the height and width of the frame while converting the quaternions to its equirectangular form.
But I still get different results after changing H=300 and W=600
Could you please tell me what should I do or the value of H and W in video football to get similar results?

Our thesis regard PARIMA as a baseline with a novel performance on prediction. But actually the error is a little high, including x_mae, y_mae and Manhattan tile error. Could you please show more information?

**Comment by sarthak-chakraborty** [comment]
The H and W in the head_orientation_lib is used to get the pixel in the equirectangular frame corresponding to the quaternion. Hence, to get the appropriate pixel representation, the range needs to be selected such that it falls within the frame size of the equirectangular image. Hence the H and W needs to be set equal to the height and width of the corresponding equirectangular frame.
